// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oa.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OaRequest struct {
	WsId                 string   `protobuf:"bytes,1,opt,name=wsId,proto3" json:"wsId,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	PageSize             string   `protobuf:"bytes,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           string   `protobuf:"bytes,5,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OaRequest) Reset()         { *m = OaRequest{} }
func (m *OaRequest) String() string { return proto.CompactTextString(m) }
func (*OaRequest) ProtoMessage()    {}
func (*OaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{0}
}

func (m *OaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaRequest.Unmarshal(m, b)
}
func (m *OaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaRequest.Marshal(b, m, deterministic)
}
func (m *OaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaRequest.Merge(m, src)
}
func (m *OaRequest) XXX_Size() int {
	return xxx_messageInfo_OaRequest.Size(m)
}
func (m *OaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OaRequest proto.InternalMessageInfo

func (m *OaRequest) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *OaRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *OaRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *OaRequest) GetPageSize() string {
	if m != nil {
		return m.PageSize
	}
	return ""
}

func (m *OaRequest) GetPageNumber() string {
	if m != nil {
		return m.PageNumber
	}
	return ""
}

func (m *OaRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type OaResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OaResponse) Reset()         { *m = OaResponse{} }
func (m *OaResponse) String() string { return proto.CompactTextString(m) }
func (*OaResponse) ProtoMessage()    {}
func (*OaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{1}
}

func (m *OaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaResponse.Unmarshal(m, b)
}
func (m *OaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaResponse.Marshal(b, m, deterministic)
}
func (m *OaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaResponse.Merge(m, src)
}
func (m *OaResponse) XXX_Size() int {
	return xxx_messageInfo_OaResponse.Size(m)
}
func (m *OaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OaResponse proto.InternalMessageInfo

func (m *OaResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OaResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OaResponse) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

//获取用户待办流程列表
type WorkflowsResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*Workflows `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WorkflowsResponse) Reset()         { *m = WorkflowsResponse{} }
func (m *WorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowsResponse) ProtoMessage()    {}
func (*WorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{2}
}

func (m *WorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowsResponse.Unmarshal(m, b)
}
func (m *WorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowsResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowsResponse.Merge(m, src)
}
func (m *WorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowsResponse.Size(m)
}
func (m *WorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowsResponse proto.InternalMessageInfo

func (m *WorkflowsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *WorkflowsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WorkflowsResponse) GetData() []*Workflows {
	if m != nil {
		return m.Data
	}
	return nil
}

type Workflows struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OaId                 string   `protobuf:"bytes,2,opt,name=oaId,proto3" json:"oaId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Date                 string   `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Source               string   `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	FinishTime           string   `protobuf:"bytes,9,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Workflows) Reset()         { *m = Workflows{} }
func (m *Workflows) String() string { return proto.CompactTextString(m) }
func (*Workflows) ProtoMessage()    {}
func (*Workflows) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{3}
}

func (m *Workflows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflows.Unmarshal(m, b)
}
func (m *Workflows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflows.Marshal(b, m, deterministic)
}
func (m *Workflows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflows.Merge(m, src)
}
func (m *Workflows) XXX_Size() int {
	return xxx_messageInfo_Workflows.Size(m)
}
func (m *Workflows) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflows.DiscardUnknown(m)
}

var xxx_messageInfo_Workflows proto.InternalMessageInfo

func (m *Workflows) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Workflows) GetOaId() string {
	if m != nil {
		return m.OaId
	}
	return ""
}

func (m *Workflows) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Workflows) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Workflows) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Workflows) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Workflows) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Workflows) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Workflows) GetFinishTime() string {
	if m != nil {
		return m.FinishTime
	}
	return ""
}

//获取用户待办流程总数
type WorkflowsTotalResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 int32    `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowsTotalResponse) Reset()         { *m = WorkflowsTotalResponse{} }
func (m *WorkflowsTotalResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowsTotalResponse) ProtoMessage()    {}
func (*WorkflowsTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{4}
}

func (m *WorkflowsTotalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowsTotalResponse.Unmarshal(m, b)
}
func (m *WorkflowsTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowsTotalResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowsTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowsTotalResponse.Merge(m, src)
}
func (m *WorkflowsTotalResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowsTotalResponse.Size(m)
}
func (m *WorkflowsTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowsTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowsTotalResponse proto.InternalMessageInfo

func (m *WorkflowsTotalResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *WorkflowsTotalResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WorkflowsTotalResponse) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type OaUserExperienceRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Badge                string   `protobuf:"bytes,2,opt,name=badge,proto3" json:"badge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OaUserExperienceRequest) Reset()         { *m = OaUserExperienceRequest{} }
func (m *OaUserExperienceRequest) String() string { return proto.CompactTextString(m) }
func (*OaUserExperienceRequest) ProtoMessage()    {}
func (*OaUserExperienceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{5}
}

func (m *OaUserExperienceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaUserExperienceRequest.Unmarshal(m, b)
}
func (m *OaUserExperienceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaUserExperienceRequest.Marshal(b, m, deterministic)
}
func (m *OaUserExperienceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaUserExperienceRequest.Merge(m, src)
}
func (m *OaUserExperienceRequest) XXX_Size() int {
	return xxx_messageInfo_OaUserExperienceRequest.Size(m)
}
func (m *OaUserExperienceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OaUserExperienceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OaUserExperienceRequest proto.InternalMessageInfo

func (m *OaUserExperienceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OaUserExperienceRequest) GetBadge() string {
	if m != nil {
		return m.Badge
	}
	return ""
}

//获取员工工作经历
type OaUserExperienceResponse struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*UserExperience `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OaUserExperienceResponse) Reset()         { *m = OaUserExperienceResponse{} }
func (m *OaUserExperienceResponse) String() string { return proto.CompactTextString(m) }
func (*OaUserExperienceResponse) ProtoMessage()    {}
func (*OaUserExperienceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{6}
}

func (m *OaUserExperienceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaUserExperienceResponse.Unmarshal(m, b)
}
func (m *OaUserExperienceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaUserExperienceResponse.Marshal(b, m, deterministic)
}
func (m *OaUserExperienceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaUserExperienceResponse.Merge(m, src)
}
func (m *OaUserExperienceResponse) XXX_Size() int {
	return xxx_messageInfo_OaUserExperienceResponse.Size(m)
}
func (m *OaUserExperienceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OaUserExperienceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OaUserExperienceResponse proto.InternalMessageInfo

func (m *OaUserExperienceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OaUserExperienceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OaUserExperienceResponse) GetData() []*UserExperience {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserExperience struct {
	ExperienceType       string   `protobuf:"bytes,1,opt,name=experience_type,json=experienceType,proto3" json:"experience_type,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ExperienceTag        string   `protobuf:"bytes,3,opt,name=experience_tag,json=experienceTag,proto3" json:"experience_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExperience) Reset()         { *m = UserExperience{} }
func (m *UserExperience) String() string { return proto.CompactTextString(m) }
func (*UserExperience) ProtoMessage()    {}
func (*UserExperience) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{7}
}

func (m *UserExperience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExperience.Unmarshal(m, b)
}
func (m *UserExperience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExperience.Marshal(b, m, deterministic)
}
func (m *UserExperience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExperience.Merge(m, src)
}
func (m *UserExperience) XXX_Size() int {
	return xxx_messageInfo_UserExperience.Size(m)
}
func (m *UserExperience) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExperience.DiscardUnknown(m)
}

var xxx_messageInfo_UserExperience proto.InternalMessageInfo

func (m *UserExperience) GetExperienceType() string {
	if m != nil {
		return m.ExperienceType
	}
	return ""
}

func (m *UserExperience) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UserExperience) GetExperienceTag() string {
	if m != nil {
		return m.ExperienceTag
	}
	return ""
}

type OaJobQualificationRequest struct {
	Badge                string   `protobuf:"bytes,1,opt,name=badge,proto3" json:"badge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OaJobQualificationRequest) Reset()         { *m = OaJobQualificationRequest{} }
func (m *OaJobQualificationRequest) String() string { return proto.CompactTextString(m) }
func (*OaJobQualificationRequest) ProtoMessage()    {}
func (*OaJobQualificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{8}
}

func (m *OaJobQualificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaJobQualificationRequest.Unmarshal(m, b)
}
func (m *OaJobQualificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaJobQualificationRequest.Marshal(b, m, deterministic)
}
func (m *OaJobQualificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaJobQualificationRequest.Merge(m, src)
}
func (m *OaJobQualificationRequest) XXX_Size() int {
	return xxx_messageInfo_OaJobQualificationRequest.Size(m)
}
func (m *OaJobQualificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OaJobQualificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OaJobQualificationRequest proto.InternalMessageInfo

func (m *OaJobQualificationRequest) GetBadge() string {
	if m != nil {
		return m.Badge
	}
	return ""
}

//获取员工任职资格记录
type OaJobQualificationResponse struct {
	Status               int32               `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*JobQualification `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OaJobQualificationResponse) Reset()         { *m = OaJobQualificationResponse{} }
func (m *OaJobQualificationResponse) String() string { return proto.CompactTextString(m) }
func (*OaJobQualificationResponse) ProtoMessage()    {}
func (*OaJobQualificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{9}
}

func (m *OaJobQualificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaJobQualificationResponse.Unmarshal(m, b)
}
func (m *OaJobQualificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaJobQualificationResponse.Marshal(b, m, deterministic)
}
func (m *OaJobQualificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaJobQualificationResponse.Merge(m, src)
}
func (m *OaJobQualificationResponse) XXX_Size() int {
	return xxx_messageInfo_OaJobQualificationResponse.Size(m)
}
func (m *OaJobQualificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OaJobQualificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OaJobQualificationResponse proto.InternalMessageInfo

func (m *OaJobQualificationResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OaJobQualificationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OaJobQualificationResponse) GetData() []*JobQualification {
	if m != nil {
		return m.Data
	}
	return nil
}

type JobQualification struct {
	StartDate              string   `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	OriginPosition         string   `protobuf:"bytes,2,opt,name=origin_position,json=originPosition,proto3" json:"origin_position,omitempty"`
	AuthenticationPosition string   `protobuf:"bytes,3,opt,name=authentication_position,json=authenticationPosition,proto3" json:"authentication_position,omitempty"`
	AuthenticationType     string   `protobuf:"bytes,4,opt,name=authentication_type,json=authenticationType,proto3" json:"authentication_type,omitempty"`
	AuthenticationJob      string   `protobuf:"bytes,5,opt,name=authentication_job,json=authenticationJob,proto3" json:"authentication_job,omitempty"`
	AbilityItem            string   `protobuf:"bytes,6,opt,name=ability_item,json=abilityItem,proto3" json:"ability_item,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *JobQualification) Reset()         { *m = JobQualification{} }
func (m *JobQualification) String() string { return proto.CompactTextString(m) }
func (*JobQualification) ProtoMessage()    {}
func (*JobQualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{10}
}

func (m *JobQualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQualification.Unmarshal(m, b)
}
func (m *JobQualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQualification.Marshal(b, m, deterministic)
}
func (m *JobQualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQualification.Merge(m, src)
}
func (m *JobQualification) XXX_Size() int {
	return xxx_messageInfo_JobQualification.Size(m)
}
func (m *JobQualification) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQualification.DiscardUnknown(m)
}

var xxx_messageInfo_JobQualification proto.InternalMessageInfo

func (m *JobQualification) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *JobQualification) GetOriginPosition() string {
	if m != nil {
		return m.OriginPosition
	}
	return ""
}

func (m *JobQualification) GetAuthenticationPosition() string {
	if m != nil {
		return m.AuthenticationPosition
	}
	return ""
}

func (m *JobQualification) GetAuthenticationType() string {
	if m != nil {
		return m.AuthenticationType
	}
	return ""
}

func (m *JobQualification) GetAuthenticationJob() string {
	if m != nil {
		return m.AuthenticationJob
	}
	return ""
}

func (m *JobQualification) GetAbilityItem() string {
	if m != nil {
		return m.AbilityItem
	}
	return ""
}

type OaPreEntryPersonInfoRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OaId                 string   `protobuf:"bytes,3,opt,name=oa_id,json=oaId,proto3" json:"oa_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OaPreEntryPersonInfoRequest) Reset()         { *m = OaPreEntryPersonInfoRequest{} }
func (m *OaPreEntryPersonInfoRequest) String() string { return proto.CompactTextString(m) }
func (*OaPreEntryPersonInfoRequest) ProtoMessage()    {}
func (*OaPreEntryPersonInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{11}
}

func (m *OaPreEntryPersonInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaPreEntryPersonInfoRequest.Unmarshal(m, b)
}
func (m *OaPreEntryPersonInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaPreEntryPersonInfoRequest.Marshal(b, m, deterministic)
}
func (m *OaPreEntryPersonInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaPreEntryPersonInfoRequest.Merge(m, src)
}
func (m *OaPreEntryPersonInfoRequest) XXX_Size() int {
	return xxx_messageInfo_OaPreEntryPersonInfoRequest.Size(m)
}
func (m *OaPreEntryPersonInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OaPreEntryPersonInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OaPreEntryPersonInfoRequest proto.InternalMessageInfo

func (m *OaPreEntryPersonInfoRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *OaPreEntryPersonInfoRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OaPreEntryPersonInfoRequest) GetOaId() string {
	if m != nil {
		return m.OaId
	}
	return ""
}

type OaPreEntryPersonSalaryResponse struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SalaryInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OaPreEntryPersonSalaryResponse) Reset()         { *m = OaPreEntryPersonSalaryResponse{} }
func (m *OaPreEntryPersonSalaryResponse) String() string { return proto.CompactTextString(m) }
func (*OaPreEntryPersonSalaryResponse) ProtoMessage()    {}
func (*OaPreEntryPersonSalaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{12}
}

func (m *OaPreEntryPersonSalaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OaPreEntryPersonSalaryResponse.Unmarshal(m, b)
}
func (m *OaPreEntryPersonSalaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OaPreEntryPersonSalaryResponse.Marshal(b, m, deterministic)
}
func (m *OaPreEntryPersonSalaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OaPreEntryPersonSalaryResponse.Merge(m, src)
}
func (m *OaPreEntryPersonSalaryResponse) XXX_Size() int {
	return xxx_messageInfo_OaPreEntryPersonSalaryResponse.Size(m)
}
func (m *OaPreEntryPersonSalaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OaPreEntryPersonSalaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OaPreEntryPersonSalaryResponse proto.InternalMessageInfo

func (m *OaPreEntryPersonSalaryResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OaPreEntryPersonSalaryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OaPreEntryPersonSalaryResponse) GetData() *SalaryInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type SalaryInfo struct {
	TrialSalary          string   `protobuf:"bytes,1,opt,name=trial_salary,json=trialSalary,proto3" json:"trial_salary,omitempty"`
	RegularSalary        string   `protobuf:"bytes,2,opt,name=regular_salary,json=regularSalary,proto3" json:"regular_salary,omitempty"`
	MonthlyBonus         string   `protobuf:"bytes,3,opt,name=monthly_bonus,json=monthlyBonus,proto3" json:"monthly_bonus,omitempty"`
	YearBonus            string   `protobuf:"bytes,4,opt,name=year_bonus,json=yearBonus,proto3" json:"year_bonus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SalaryInfo) Reset()         { *m = SalaryInfo{} }
func (m *SalaryInfo) String() string { return proto.CompactTextString(m) }
func (*SalaryInfo) ProtoMessage()    {}
func (*SalaryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163989536c1bfb1, []int{13}
}

func (m *SalaryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SalaryInfo.Unmarshal(m, b)
}
func (m *SalaryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SalaryInfo.Marshal(b, m, deterministic)
}
func (m *SalaryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SalaryInfo.Merge(m, src)
}
func (m *SalaryInfo) XXX_Size() int {
	return xxx_messageInfo_SalaryInfo.Size(m)
}
func (m *SalaryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SalaryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SalaryInfo proto.InternalMessageInfo

func (m *SalaryInfo) GetTrialSalary() string {
	if m != nil {
		return m.TrialSalary
	}
	return ""
}

func (m *SalaryInfo) GetRegularSalary() string {
	if m != nil {
		return m.RegularSalary
	}
	return ""
}

func (m *SalaryInfo) GetMonthlyBonus() string {
	if m != nil {
		return m.MonthlyBonus
	}
	return ""
}

func (m *SalaryInfo) GetYearBonus() string {
	if m != nil {
		return m.YearBonus
	}
	return ""
}

func init() {
	proto.RegisterType((*OaRequest)(nil), "proto.OaRequest")
	proto.RegisterType((*OaResponse)(nil), "proto.OaResponse")
	proto.RegisterType((*WorkflowsResponse)(nil), "proto.WorkflowsResponse")
	proto.RegisterType((*Workflows)(nil), "proto.Workflows")
	proto.RegisterType((*WorkflowsTotalResponse)(nil), "proto.WorkflowsTotalResponse")
	proto.RegisterType((*OaUserExperienceRequest)(nil), "proto.OaUserExperienceRequest")
	proto.RegisterType((*OaUserExperienceResponse)(nil), "proto.OaUserExperienceResponse")
	proto.RegisterType((*UserExperience)(nil), "proto.UserExperience")
	proto.RegisterType((*OaJobQualificationRequest)(nil), "proto.OaJobQualificationRequest")
	proto.RegisterType((*OaJobQualificationResponse)(nil), "proto.OaJobQualificationResponse")
	proto.RegisterType((*JobQualification)(nil), "proto.JobQualification")
	proto.RegisterType((*OaPreEntryPersonInfoRequest)(nil), "proto.OaPreEntryPersonInfoRequest")
	proto.RegisterType((*OaPreEntryPersonSalaryResponse)(nil), "proto.OaPreEntryPersonSalaryResponse")
	proto.RegisterType((*SalaryInfo)(nil), "proto.SalaryInfo")
}

func init() { proto.RegisterFile("oa.proto", fileDescriptor_3163989536c1bfb1) }

var fileDescriptor_3163989536c1bfb1 = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x72, 0xdb, 0x44,
	0x14, 0x1d, 0xb9, 0x76, 0x1a, 0x5f, 0x37, 0x4e, 0xb2, 0x71, 0x1c, 0x55, 0x4d, 0x43, 0x2a, 0xc8,
	0x34, 0x0c, 0x13, 0x7b, 0x08, 0x0f, 0x3c, 0x53, 0x28, 0x4c, 0xfa, 0x80, 0x43, 0x1a, 0x86, 0x19,
	0x1e, 0x6a, 0x56, 0xf1, 0xda, 0xde, 0x46, 0xd6, 0xaa, 0xbb, 0xab, 0x49, 0x05, 0x4f, 0x30, 0xfc,
	0x01, 0x33, 0x3c, 0xf0, 0x03, 0xfc, 0x05, 0xff, 0xc0, 0xf0, 0x0b, 0x7c, 0x08, 0xb3, 0x77, 0xd7,
	0xb2, 0xe4, 0x24, 0x3c, 0x34, 0x4f, 0xd6, 0x3d, 0xf7, 0xee, 0xbd, 0x47, 0xe7, 0xae, 0x8e, 0x61,
	0x55, 0xd0, 0x5e, 0x2a, 0x85, 0x16, 0xa4, 0x81, 0x3f, 0xc1, 0xee, 0x44, 0x88, 0x49, 0xcc, 0xfa,
	0x34, 0xe5, 0x7d, 0x9a, 0x24, 0x42, 0x53, 0xcd, 0x45, 0xa2, 0x6c, 0x51, 0xf0, 0xd0, 0x65, 0x31,
	0x8a, 0xb2, 0x71, 0x9f, 0x26, 0xb9, 0x4d, 0x85, 0x7f, 0x7a, 0xd0, 0x1c, 0xd0, 0x33, 0xf6, 0x26,
	0x63, 0x4a, 0x13, 0x02, 0xf5, 0x2b, 0x75, 0x32, 0xf2, 0xbd, 0x7d, 0xef, 0xb0, 0x79, 0x86, 0xcf,
	0x64, 0x17, 0x9a, 0x4a, 0x53, 0xa9, 0xbf, 0xa0, 0x9a, 0xf9, 0x35, 0x4c, 0x2c, 0x00, 0xe2, 0xc3,
	0x7d, 0x96, 0x8c, 0x30, 0x77, 0x0f, 0x73, 0xf3, 0x90, 0x04, 0xb0, 0x9a, 0xd2, 0x09, 0x7b, 0xc9,
	0x7f, 0x64, 0x7e, 0x1d, 0x53, 0x45, 0x4c, 0xf6, 0x00, 0xcc, 0xf3, 0xd7, 0xd9, 0x2c, 0x62, 0xd2,
	0x6f, 0x60, 0xb6, 0x84, 0x18, 0x1e, 0x3a, 0x4f, 0x99, 0xbf, 0x62, 0x79, 0x98, 0xe7, 0x70, 0x0a,
	0x60, 0x88, 0xaa, 0x54, 0x24, 0x8a, 0x91, 0x2e, 0xac, 0x28, 0x4d, 0x75, 0xa6, 0x90, 0x6b, 0xe3,
	0xcc, 0x45, 0x86, 0xcf, 0x8c, 0x29, 0x45, 0x27, 0x73, 0xae, 0xf3, 0x90, 0x1c, 0x42, 0x7d, 0x44,
	0x35, 0x45, 0x9a, 0xad, 0xe3, 0x4e, 0xcf, 0x6a, 0xd2, 0x9b, 0x6b, 0xd2, 0xfb, 0x2c, 0xc9, 0xcf,
	0xb0, 0x22, 0xbc, 0x84, 0xcd, 0xef, 0x84, 0xbc, 0x1c, 0xc7, 0xe2, 0x4a, 0xdd, 0x61, 0xe0, 0x07,
	0xc5, 0xc0, 0x7b, 0x87, 0xad, 0xe3, 0x0d, 0x3b, 0xa9, 0xb7, 0xe8, 0x6c, 0x87, 0xfd, 0xed, 0x41,
	0xb3, 0xc0, 0x48, 0x1b, 0x6a, 0x7c, 0x2e, 0x7f, 0x8d, 0x8f, 0x8c, 0x10, 0x82, 0x9e, 0x8c, 0x5c,
	0x6b, 0x7c, 0x26, 0x1d, 0x68, 0x68, 0xae, 0xe3, 0xb9, 0xe0, 0x36, 0x30, 0x95, 0x31, 0x4f, 0x2e,
	0x9d, 0xd4, 0xf8, 0x5c, 0xe2, 0xdc, 0xa8, 0x70, 0x26, 0xc8, 0xac, 0x90, 0xd7, 0x3c, 0x63, 0xad,
	0xc8, 0xe4, 0x05, 0xf3, 0xef, 0x23, 0xea, 0xa2, 0x62, 0x15, 0xab, 0x8b, 0x55, 0x98, 0xf5, 0x8d,
	0x79, 0xc2, 0xd5, 0xf4, 0x9c, 0xcf, 0x98, 0xdf, 0xb4, 0xeb, 0x5b, 0x20, 0xe1, 0x2b, 0xe8, 0x16,
	0xaf, 0x74, 0x2e, 0x34, 0x8d, 0xef, 0xa0, 0x22, 0x29, 0xad, 0xad, 0xe1, 0x34, 0xfb, 0x1c, 0x76,
	0x06, 0xf4, 0x5b, 0xc5, 0xe4, 0xf3, 0xb7, 0x29, 0x93, 0x9c, 0x25, 0x17, 0xac, 0x74, 0x83, 0x91,
	0xae, 0x57, 0xa2, 0xdb, 0x81, 0x46, 0x44, 0x47, 0x45, 0x6b, 0x1b, 0x84, 0x57, 0xe0, 0x5f, 0x6f,
	0xf2, 0xce, 0x34, 0x3f, 0xac, 0x2c, 0x7b, 0xdb, 0x2d, 0x7b, 0xa9, 0xbd, 0x65, 0xff, 0x16, 0xda,
	0x55, 0x9c, 0x3c, 0x85, 0x75, 0x56, 0x44, 0xc3, 0x12, 0xff, 0xf6, 0x02, 0x3e, 0x37, 0x6f, 0xd2,
	0x85, 0x95, 0x11, 0xd3, 0x94, 0xc7, 0x6e, 0xbc, 0x8b, 0xc8, 0x01, 0xb4, 0xcb, 0x0d, 0xe8, 0xc4,
	0xdd, 0x8d, 0xb5, 0xd2, 0x79, 0x3a, 0x09, 0x3f, 0x86, 0x87, 0x03, 0xfa, 0x42, 0x44, 0xdf, 0x64,
	0x34, 0xe6, 0x63, 0x7e, 0x81, 0x26, 0x31, 0x57, 0xae, 0x50, 0xc9, 0x2b, 0xab, 0xf4, 0x13, 0x04,
	0x37, 0x1d, 0x79, 0x67, 0x9d, 0x3e, 0xaa, 0xe8, 0xb4, 0xe3, 0x74, 0xba, 0x36, 0xc0, 0x2a, 0xf5,
	0x7b, 0x0d, 0x36, 0x96, 0x53, 0xe4, 0x31, 0x00, 0xda, 0xcf, 0x10, 0xaf, 0xb0, 0xb7, 0x6c, 0x48,
	0x4f, 0x61, 0x5d, 0x48, 0x3e, 0xe1, 0xc9, 0x30, 0x15, 0x8a, 0x9b, 0x13, 0x8e, 0x42, 0xdb, 0xc2,
	0xa7, 0x0e, 0x25, 0x9f, 0xc2, 0x0e, 0xcd, 0xf4, 0x94, 0x25, 0xda, 0x75, 0x5e, 0x1c, 0xb0, 0xe2,
	0x75, 0xab, 0xe9, 0xe2, 0x60, 0x1f, 0xb6, 0x96, 0x0e, 0xe2, 0xc6, 0xec, 0x87, 0x47, 0xaa, 0x29,
	0xdc, 0xda, 0x11, 0x2c, 0xa1, 0xc3, 0xd7, 0x22, 0x72, 0xae, 0xb7, 0x59, 0xcd, 0xbc, 0x10, 0x11,
	0x79, 0x02, 0x0f, 0x68, 0xc4, 0x63, 0xae, 0xf3, 0x21, 0xd7, 0x6c, 0xe6, 0xbe, 0xd2, 0x96, 0xc3,
	0x4e, 0x34, 0x9b, 0x85, 0xaf, 0xe0, 0xd1, 0x80, 0x9e, 0x4a, 0xf6, 0x3c, 0xd1, 0x32, 0x3f, 0x65,
	0x52, 0x89, 0xe4, 0x24, 0x19, 0x8b, 0xd2, 0x2a, 0xd3, 0xa9, 0x48, 0x8a, 0x55, 0x62, 0x60, 0x50,
	0x36, 0x5b, 0xdc, 0x1d, 0x1b, 0x90, 0x2d, 0x68, 0x08, 0x3a, 0xe4, 0x23, 0xf7, 0xd2, 0x68, 0x31,
	0x61, 0x0e, 0x7b, 0xcb, 0xfd, 0x5f, 0xd2, 0x98, 0xca, 0xfc, 0x0e, 0x9b, 0x3f, 0xa8, 0xf8, 0xef,
	0xa6, 0xdb, 0xbc, 0x6d, 0x8b, 0xe4, 0xed, 0xce, 0xff, 0xf0, 0x00, 0x16, 0xa0, 0x11, 0x43, 0x4b,
	0x4e, 0xe3, 0xa1, 0x42, 0xcc, 0xbd, 0x51, 0x0b, 0x31, 0x5b, 0x66, 0x2e, 0xbf, 0x64, 0x93, 0x2c,
	0xa6, 0x72, 0x5e, 0x64, 0x27, 0xaf, 0x39, 0xd4, 0x95, 0xbd, 0x0f, 0x6b, 0x33, 0x91, 0xe8, 0x69,
	0x9c, 0x0f, 0x23, 0x91, 0x64, 0xca, 0xbd, 0xf0, 0x03, 0x07, 0x3e, 0x33, 0x98, 0xb9, 0x5c, 0x39,
	0xa3, 0xd2, 0x55, 0xd8, 0x95, 0x36, 0x0d, 0x82, 0xe9, 0xe3, 0xbf, 0xea, 0x50, 0x1b, 0x50, 0x72,
	0x0a, 0xad, 0x01, 0x35, 0x0e, 0xf7, 0x25, 0x9a, 0xf6, 0xdc, 0xda, 0x8b, 0xff, 0xd1, 0xc0, 0xbf,
	0x66, 0xf6, 0x4e, 0xb7, 0x70, 0xfb, 0x97, 0x7f, 0xfe, 0xfd, 0xad, 0xb6, 0x4e, 0xd6, 0xfa, 0x82,
	0xf6, 0xaf, 0x0a, 0xdf, 0xff, 0x01, 0x36, 0x4a, 0x1d, 0xd1, 0x33, 0x6f, 0x68, 0xfb, 0x78, 0xb9,
	0x6d, 0xc5, 0x5c, 0xc3, 0x47, 0xd8, 0x7b, 0x9b, 0x6c, 0x55, 0x7a, 0xf7, 0x35, 0x76, 0xcb, 0xa1,
	0x63, 0xed, 0xce, 0x1c, 0x2e, 0x79, 0xcf, 0x5e, 0x31, 0xe5, 0x46, 0x43, 0x0d, 0xde, 0xbb, 0x35,
	0xef, 0xa6, 0xee, 0xe3, 0xd4, 0x80, 0xf8, 0x66, 0x6a, 0xa6, 0x98, 0xc4, 0xd1, 0x47, 0x0b, 0xe7,
	0x21, 0x3f, 0x7b, 0xd0, 0xb5, 0xc7, 0xaf, 0x7d, 0xcc, 0xfb, 0x45, 0xf7, 0x5b, 0x6c, 0x29, 0x78,
	0xf2, 0x3f, 0x15, 0x8e, 0x41, 0x88, 0x0c, 0x76, 0x49, 0x50, 0x30, 0x78, 0x2d, 0xa2, 0xa3, 0x37,
	0x95, 0x41, 0xbf, 0x7a, 0xc6, 0xfb, 0xbe, 0x62, 0xfa, 0xa6, 0x5b, 0x4d, 0xc2, 0x62, 0xc8, 0xad,
	0x1f, 0x55, 0x70, 0x70, 0x4b, 0x4d, 0xf5, 0xc3, 0x08, 0x77, 0x91, 0x4c, 0x97, 0x74, 0x0c, 0x99,
	0x54, 0xb2, 0x23, 0x66, 0x4a, 0xfb, 0xf6, 0x66, 0x3e, 0xab, 0x7f, 0x5f, 0x4b, 0xa3, 0x68, 0x05,
	0x3b, 0x7d, 0xf2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x62, 0x14, 0x92, 0xc7, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OaClient is the client API for Oa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OaClient interface {
	//获取用户待办流程列表 Done
	OaWorkFlows(ctx context.Context, in *OaRequest, opts ...grpc.CallOption) (*WorkflowsResponse, error)
	//获取指定用户待办流程总数
	OaWorkFlowsTotal(ctx context.Context, in *OaRequest, opts ...grpc.CallOption) (*WorkflowsTotalResponse, error)
	//获取员工工作经历
	OaUserWorkExperience(ctx context.Context, in *OaUserExperienceRequest, opts ...grpc.CallOption) (*OaUserExperienceResponse, error)
	//获取员工任职资格记录
	OaUserJobQualification(ctx context.Context, in *OaJobQualificationRequest, opts ...grpc.CallOption) (*OaJobQualificationResponse, error)
	// 根据手机号获取预入职者的薪资信息
	OaGetPreEntryPersonSalary(ctx context.Context, in *OaPreEntryPersonInfoRequest, opts ...grpc.CallOption) (*OaPreEntryPersonSalaryResponse, error)
}

type oaClient struct {
	cc *grpc.ClientConn
}

func NewOaClient(cc *grpc.ClientConn) OaClient {
	return &oaClient{cc}
}

func (c *oaClient) OaWorkFlows(ctx context.Context, in *OaRequest, opts ...grpc.CallOption) (*WorkflowsResponse, error) {
	out := new(WorkflowsResponse)
	err := c.cc.Invoke(ctx, "/proto.Oa/OaWorkFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) OaWorkFlowsTotal(ctx context.Context, in *OaRequest, opts ...grpc.CallOption) (*WorkflowsTotalResponse, error) {
	out := new(WorkflowsTotalResponse)
	err := c.cc.Invoke(ctx, "/proto.Oa/OaWorkFlowsTotal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) OaUserWorkExperience(ctx context.Context, in *OaUserExperienceRequest, opts ...grpc.CallOption) (*OaUserExperienceResponse, error) {
	out := new(OaUserExperienceResponse)
	err := c.cc.Invoke(ctx, "/proto.Oa/OaUserWorkExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) OaUserJobQualification(ctx context.Context, in *OaJobQualificationRequest, opts ...grpc.CallOption) (*OaJobQualificationResponse, error) {
	out := new(OaJobQualificationResponse)
	err := c.cc.Invoke(ctx, "/proto.Oa/OaUserJobQualification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) OaGetPreEntryPersonSalary(ctx context.Context, in *OaPreEntryPersonInfoRequest, opts ...grpc.CallOption) (*OaPreEntryPersonSalaryResponse, error) {
	out := new(OaPreEntryPersonSalaryResponse)
	err := c.cc.Invoke(ctx, "/proto.Oa/OaGetPreEntryPersonSalary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OaServer is the server API for Oa service.
type OaServer interface {
	//获取用户待办流程列表 Done
	OaWorkFlows(context.Context, *OaRequest) (*WorkflowsResponse, error)
	//获取指定用户待办流程总数
	OaWorkFlowsTotal(context.Context, *OaRequest) (*WorkflowsTotalResponse, error)
	//获取员工工作经历
	OaUserWorkExperience(context.Context, *OaUserExperienceRequest) (*OaUserExperienceResponse, error)
	//获取员工任职资格记录
	OaUserJobQualification(context.Context, *OaJobQualificationRequest) (*OaJobQualificationResponse, error)
	// 根据手机号获取预入职者的薪资信息
	OaGetPreEntryPersonSalary(context.Context, *OaPreEntryPersonInfoRequest) (*OaPreEntryPersonSalaryResponse, error)
}

func RegisterOaServer(s *grpc.Server, srv OaServer) {
	s.RegisterService(&_Oa_serviceDesc, srv)
}

func _Oa_OaWorkFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).OaWorkFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Oa/OaWorkFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).OaWorkFlows(ctx, req.(*OaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_OaWorkFlowsTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).OaWorkFlowsTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Oa/OaWorkFlowsTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).OaWorkFlowsTotal(ctx, req.(*OaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_OaUserWorkExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OaUserExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).OaUserWorkExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Oa/OaUserWorkExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).OaUserWorkExperience(ctx, req.(*OaUserExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_OaUserJobQualification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OaJobQualificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).OaUserJobQualification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Oa/OaUserJobQualification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).OaUserJobQualification(ctx, req.(*OaJobQualificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_OaGetPreEntryPersonSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OaPreEntryPersonInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).OaGetPreEntryPersonSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Oa/OaGetPreEntryPersonSalary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).OaGetPreEntryPersonSalary(ctx, req.(*OaPreEntryPersonInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Oa",
	HandlerType: (*OaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OaWorkFlows",
			Handler:    _Oa_OaWorkFlows_Handler,
		},
		{
			MethodName: "OaWorkFlowsTotal",
			Handler:    _Oa_OaWorkFlowsTotal_Handler,
		},
		{
			MethodName: "OaUserWorkExperience",
			Handler:    _Oa_OaUserWorkExperience_Handler,
		},
		{
			MethodName: "OaUserJobQualification",
			Handler:    _Oa_OaUserJobQualification_Handler,
		},
		{
			MethodName: "OaGetPreEntryPersonSalary",
			Handler:    _Oa_OaGetPreEntryPersonSalary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oa.proto",
}
